### ISSUE TITLE
GFF File

### ISSUE THREAD

**Issue by schae234** [drtamermansour/horse_trans#5]
Hi @drtamermansour ,

I was wondering if you added any additional transcripts to the GFF file you were using or it it just the GFFs you download [here](https://github.com/drtamermansour/horse_trans/blob/9a9b28b47a150216f197327def1230d8c87f65db/main.sh#L205)?

Thanks!

**Comment by drtamermansour** [comment]
Hi Rob,
Unfortunately, I am out of office with very limited internet connection. I will check the link and contact you back next week. Hopefully this is ok with you.

Regards

Tamer

**Comment by schae234** [comment]
No Problem!

Thanks
